name = "benchmarks"

account_id = ""

workers_dev = true  # Deploy ke workers.dev subdomain, ubah ke false jika ingin menggunakan custom domain

[env.production]
name = "benchmarks"
route = "https://benchmarks.chrisyuda.workers.dev/*"  