name = "benchmarks"
type = "javascript"

account_id = "2f83e4d2a261df7a84eeb206abee0d76"
zone_id = "9d9883d6685e401c83db85029ac2e7140c4f3"  # Hapus baris ini jika tidak menggunakan zona spesifik

workers_dev = true  # Deploy ke workers.dev subdomain, ubah ke false jika ingin menggunakan custom domain

[env.production]
name = "benchmarks"
route = "https://benchmarks.chrisyuda.workers.dev/*"  