name = "benchmarks"
type = "javascript"

account_id = ""
zone_id = ""  # Hapus baris ini jika tidak menggunakan zona spesifik

workers_dev = true  # Deploy ke workers.dev subdomain, ubah ke false jika ingin menggunakan custom domain

[env.production]
name = "benchmarks"
route = "https://benchmarks.chrisyuda.workers.dev/*"  